# Generated by Django 4.1.3 on 2022-11-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pages.page'),
        ),
    ]
