# Generated by Django 4.1.3 on 2022-11-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='page',
        ),
    ]
