services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    links:
      - "db:db"
  redis:
    image: "redis:alpine"
  celery:
    build: .
    entrypoint: sh ./entrypointCelery.sh
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
