services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${PGR_USER}
      - POSTGRES_PASSWORD=${PGR_PASSWORD}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - ${PORTS}
    environment:
      - POSTGRES_NAME=${PGR_NAME}
      - POSTGRES_USER=${PGR_USER}
      - POSTGRES_PASSWORD=${PGR_PASSWORD}
    depends_on:
      - db