version: '3.7'
services:
  web:
    command: python ~/Innotter/manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - /home/ulyana474/Innotter
    # ports:
    #   - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: