# Generated by Django 4.1.3 on 2022-11-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tag'),
        ('pages', '0004_remove_page_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(related_name='pages_tags', to='users.tag'),
        ),
    ]
